env:
  browser: true
  worker: true
  es2021: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 12
  sourceType: module
globals:
  Terminal: "readonly"
rules:
  no-constant-condition:
    - error
    - checkLoops: false
  semi: error
  eqeqeq: error
  comma-dangle:
    - error
    - always-multiline
  no-debugger: off
  no-throw-literal: error
  require-await: error
  no-return-await: error
