env:
  browser: true
  worker: true
  es2021: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 12
  sourceType: module
globals:
  Terminal: "readonly"
rules:
  no-constant-condition:
    - error
    - checkLoops: false
  semi: error
