#!/usr/bin/env bash
set -e

cd "$OSOAP_ROOT"

if [ "$CLEAN" = "1" ]; then
  rm -rf sysroot
  echo "Purging sysroot"
  mkdir -p sysroot
fi

pushd osoap-libc

if [ "$CLEAN" = "1" ]; then
  make distclean
  ./configure-wasm
fi
make && make install

popd # osoap-libc

pushd libasyncify

make clean
make
make install

popd # libasyncify

pushd libstubfork

make clean
make
make install

popd # libstubfork

if [ "$CLEAN" = "1" ]; then
  configure_arg=
else
  configure_arg=--no-configure
fi

OSoap/tools/compile-packages/ncurses ${configure_arg}

OSoap/tools/compile-packages/bash ${configure_arg}

OSoap/tools/compile-packages/coreutils ${configure_arg}

OSoap/tools/compile-packages/readline

pushd OSoap

if [ "$CLEAN" = "1" ]; then
  make clean
fi

make

popd # OSoap
