#!/usr/bin/env bash
set -e

cd "$OPAM_ROOT"

if [ "$CLEAN" = "1" ]; then
  rm -rf sysroot
  mkdir -p sysroot
fi

pushd osoap-libc

if [ "$CLEAN" = "1" ]; then
  make distclean
  ./configure-wasm
fi
make && make install

popd # osoap-libc

if [ "$CLEAN" = "1"]; then
  $ncurses_configure=
else
  $ncurses_configure=--no-configure
fi

OSoap/tools/compile-packages/ncurses ${ncurses_configure}

OSoap/tools/compile-packages/bash

OSoap/tools/compile-packages/readline

pushd OSoap

if [ "$CLEAN" = "1" ]; then
  make clean
fi

make

popd # OSoap
