#!/usr/bin/env bash
set -e

CONFIGURE=yes
while [[ $# -gt 0 ]]; do
  key="$1"
  case "$key" in
    --no-configure)
      CONFIGURE=no
      shift # past argument
      ;;
  esac
done

cd "${OSOAP_ROOT}/ncurses-6.2"
TARGET=wasm32
SYSROOT="${OSOAP_ROOT}/sysroot"
export CC="clang "
export CFLAGS="--target=${TARGET} --sysroot=${SYSROOT} -g -pthread"
export BUILD_CC="clang"
export BUILD_CFLAGS="-g"
export LD="wasm-ld"
export LDFLAGS="-Wl,--import-memory -Wl,--shared-memory -Wl,--max-memory=4294967296"
export AR="llvm-ar"
export RANLIB="llvm-ranlib"
if [ "$CONFIGURE" = "yes" ]; then
  make distclean || true
  ./configure \
    --prefix="${SYSROOT}" \
    --host="${TARGET}" \
    --without-cxx \
    --without-manpages \
    --disable-stripping \
    --enable-overwrite \
    --with-default-terminfo-dir="/sysroot/share/terminfo" \
    --with-terminfo-dirs="/sysroot/share/terminfo"
else
  make clean
fi
make
make install

pushd test
if [ "$CONFIGURE" = "yes" ]; then
  make distclean || true
  ./configure --prefix="${SYSROOT}" --host="${TARGET}" --disable-stripping
else
  make clean
fi
make
popd # test
